#!/bin/sh
#PBS -j oe
#PBS -l walltime=18:00:00,select=1:ncpus=16:mpiprocs=16:mem=3072mb
#


module load mpi
module load vtk
module load gcc
module load mooseframework
# module load intel-suite mpi

cp -r $WORK/DropZone/MyRuns/* $TMPDIR
cp -r $WORK/Outputs/Fattbert2D_Con1_R1_out.e $TMPDIR

pbsexec -grace 5 mpiexec $WORK/mooseFR/EColi/EColi-opt -i ./Fattbert2D_Con1_R2.i
cp $TMPDIR/*.e -f $WORK/Outputs
cp $TMPDIR/*.i -f $WORK/Outputs

echo "QZ Done"
