#!/bin/sh
#PBS -j oe
#PBS -l walltime=12:00:00,select=1:ncpus=16:mpiprocs=16:mem=1024mb
#

module load mpi
module load vtk
module load gcc
module load mooseframework
# module load intel-suite mpi

cp -r $WORK/DropZone/TiAl_2D_NoiseB/*.i $TMPDIR
cp -r $WORK/DropZone/TiAl_2D_NoiseB/TiAl_NoiseB_R0_out.e $TMPDIR
pbsexec -grace 30 mpiexec $WORK/mooseFR/EColi/EColi-opt -i ./TiAl_NoiseB_R1.i
cp -f $TMPDIR/TiAl_NoiseB_R1_out.e  $WORK/DropZone/TiAl_2D_NoiseB/TiAl_NoiseB_R0_out.e

echo "QZ Done"
