#!/bin/sh
#PBS -j oe
#PBS -l walltime=18:00:00,select=1:ncpus=16:mpiprocs=16:mem=3072mb
#

module load mpi
module load vtk
module load gcc
module load mooseframework
# module load intel-suite mpi

cp -r $WORK/DropZone/NoiseGrad1/NoiseSeed/* $TMPDIR
# cp -r $WORK/DropZone/KenelToHPC/Outputs/TiAl_NoiseB_R0_out.e $TMPDIR
pbsexec -grace 30 mpiexec $WORK/mooseFR/EColi/EColi-opt -i ./Jun8Noise.i
cp -f $TMPDIR/*.e  $WORK/DropZone/NoiseGrad1/NoiseSeed/

# qsub $WORK/DropZone/NoiseGrad1/NoiseSeed/Kenel_1D_C46T1_R0.qsub
