#!/bin/sh
#PBS -j oe
#PBS -l walltime=12:00:00,select=1:ncpus=16:mpiprocs=16:mem=1024mb
#

module load mpi
module load vtk
module load gcc
module load mooseframework
# module load intel-suite mpi

cp -r $WORK/DropZone/Fattbert1DGen/*.i $TMPDIR
cp -r $WORK/Outputs/Fattbert1DGen/Fattbert1D_Con1_R1_out.e $TMPDIR
pbsexec -grace 30 mpiexec $WORK/mooseFR/EColi/EColi-opt -i ./Fattbert1D_Con1_R2.i
cp -f $TMPDIR/Fattbert1D_Con1_R2*  $WORK/Outputs/Fattbert1DGen/

echo "QZ Done"
